# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: windows-latest

stages:
- stage : CI
  displayName: CI Stage
  jobs:
  - job: build
    displayName: Build
    steps:
    - script: echo This is a BUILD job
      displayName: 'Build project'
- stage: CD
  displayName: CD Stage
  jobs:
  - deployment: deploy
    displayName: Deploy
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo This is a DEPLOYMENT job
            displayName: 'Deploy project'
      
